theme: jekyll-theme-slate
title: The homepage of LIJUNHONG 
description: What you will find here are links to projects, publications, and repositories related to the former.
plugins:
  - jemoji
url: "https://rrijunhong.github.io/"
markdown: kramdown
